### ISSUE TITLE
Will not transmit data over bluetooth

### ISSUE THREAD

**Issue by Joshua-Kirk** [Joshua-Kirk/SwipeShare#1]
Bluetooth will pair perfectly and the data can be located by the user. Though when the it is time to send the data it will not fail, nor will it transmit.

**Comment by Lincarl7236** [comment]
I have cloned the code ,and build the apk of bluetooth. But, I could not transmit photo, data,or other thing. The system I used is Android 5.0.2. What can I do to solve the question?

**Comment by Joshua-Kirk** [comment]
This project is ongoing and not finished, the read me is what the goal of
this project is. To correct your issue I would ensure that the manifest
file is updated with your version of Android but also there is a bug in the
ManagedConnections file. This is the cause for not transmitting data and
thus the reason I put this project on GitHub. I do not have the time to
properly work all of the issues and I seek other developers to fork and
assist in the creation of it. If you have some time and skills please take
a look and see if you can find the bug.
